#!/usr/bin/env python3
"""Cross-Conference Organizer Ingestion CLI for AGNTCon Europe 2026.

Ingests structured JSON research manifests generated by external AI assistants
(KIMI swarm) at data/external_conferences.json.

Tags imported organizers with:
- cohort: "cohort_external_organizers"
- source: "kimi_swarm"
- legal_basis: "legitimate_interest_opensource_peer" (GDPR Article 6(1)(f))

Ingests into data/contacts.json, updates data/contacts_summary.json, and
enables Template D outreach generation.
"""

import argparse
import datetime
import json
import logging
import re
import sys
from pathlib import Path
from typing import Any

HUB_DIR = Path(__file__).resolve().parent.parent
DEFAULT_INPUT = HUB_DIR / "data" / "external_conferences.json"
DEFAULT_CONTACTS = HUB_DIR / "data" / "contacts.json"
DEFAULT_SUMMARY = HUB_DIR / "data" / "contacts_summary.json"
DEFAULT_DB = HUB_DIR / "data" / "outreach_private.sqlite"

sys.path.insert(0, str(HUB_DIR))
try:
    from scripts.verify_contacts import verify_single_contact
except ImportError:
    verify_single_contact = None

try:
    import outreach_db
except ImportError:
    outreach_db = None

logger = logging.getLogger("import_external_conferences")


def slugify(text: str) -> str:
    """Produces clean snake_case ascii identifier."""
    if not text:
        return "unknown"
    s = text.lower().strip()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[-\s]+", "_", s)
    return s.strip("_") or "unknown"


def validate_conference_manifest(data: dict[str, Any]) -> list[str]:
    """Validates the structure of the incoming external conference research manifest."""
    errors = []
    if not isinstance(data, dict):
        return ["Manifest root must be a JSON object"]

    confs = data.get("conferences")
    if not isinstance(confs, list):
        return ["Manifest must contain a 'conferences' list"]

    required_conf_fields = ("name", "dates", "city", "website", "schedule_url")
    for i, conf in enumerate(confs):
        if not isinstance(conf, dict):
            errors.append(f"Conference #{i} must be a dictionary")
            continue
        for rf in required_conf_fields:
            if not conf.get(rf):
                errors.append(f"Conference #{i} missing required field: '{rf}'")

        orgs = conf.get("organizers")
        if not isinstance(orgs, list):
            errors.append(f"Conference '{conf.get('name', i)}' must have an 'organizers' list")
        else:
            for j, org in enumerate(orgs):
                if not isinstance(org, dict) or not org.get("name"):
                    errors.append(f"Conference '{conf.get('name', i)}' organizer #{j} missing 'name'")

    return errors


def import_external_conferences(
    input_path: Path | str = DEFAULT_INPUT,
    contacts_path: Path | str = DEFAULT_CONTACTS,
    summary_path: Path | str = DEFAULT_SUMMARY,
    db_path: Path | str = DEFAULT_DB,
) -> dict[str, Any]:
    input_path = Path(input_path)
    contacts_path = Path(contacts_path)
    summary_path = Path(summary_path)
    db_path = Path(db_path)

    if not input_path.exists():
        raise FileNotFoundError(f"External conferences manifest not found at {input_path}")

    with open(input_path, encoding="utf-8") as f:
        manifest_data = json.load(f)

    validation_errors = validate_conference_manifest(manifest_data)
    if validation_errors:
        raise ValueError(f"Manifest validation failed with {len(validation_errors)} error(s): {validation_errors[:3]}")

    # Load existing contacts.json
    contacts_data: dict[str, Any] = {
        "updated_at": datetime.datetime.now(datetime.UTC).isoformat(),
        "total_speakers": 0,
        "total_organizers": 0,
        "cohorts_summary": {},
        "speakers": [],
        "organizers": [],
        "external_organizers": [],
    }
    if contacts_path.exists():
        try:
            with open(contacts_path, encoding="utf-8") as cf:
                contacts_data = json.load(cf)
        except Exception as e:
            logger.warning(f"Could not load existing contacts.json, initializing fresh: {e}")

    existing_ext_orgs = contacts_data.get("external_organizers", [])
    existing_keys = {
        (o.get("name", "").lower(), (o.get("conference_name") or o.get("conference", "")).lower())
        for o in existing_ext_orgs
    }

    newly_imported = 0
    updated_count = 0

    for conf in manifest_data.get("conferences", []):
        conf_name = conf["name"]
        conf_web = conf["website"]

        for org in conf.get("organizers", []):
            name = org["name"]
            key = (name.lower(), conf_name.lower())
            oid = f"org_ext_{slugify(conf_name)}_{slugify(name)}"

            org_record = {
                "id": oid,
                "name": name,
                "role": org.get("role", "Organizer"),
                "company": org.get("company", ""),
                "bio": org.get("bio", ""),
                "conference_name": conf_name,
                "conference_website": conf_web,
                "conference": conf_name,
                "linkedin_url": org.get("linkedin_url"),
                "twitter_url": org.get("twitter_url"),
                "email": org.get("email"),
                "cohort": "cohort_external_organizers",
                "source": "kimi_swarm",
                "legal_basis": "legitimate_interest_opensource_peer",
            }

            # Run offline verification heuristic if available
            if verify_single_contact:
                verif = verify_single_contact(org_record)
                org_record["verification_status"] = verif["status"]
                org_record["verification"] = verif
            else:
                org_record["verification_status"] = "unverified"

            if key not in existing_keys:
                existing_ext_orgs.append(org_record)
                existing_keys.add(key)
                newly_imported += 1
            else:
                # Update existing record
                for idx, item in enumerate(existing_ext_orgs):
                    item_key = (item.get("name", "").lower(), (item.get("conference_name") or item.get("conference", "")).lower())
                    if item_key == key:
                        existing_ext_orgs[idx] = org_record
                        updated_count += 1
                        break

    contacts_data["external_organizers"] = existing_ext_orgs
    contacts_data["updated_at"] = datetime.datetime.now(datetime.UTC).isoformat()

    # Recalculate summary
    speakers = contacts_data.get("speakers", [])
    organizers = contacts_data.get("organizers", [])
    missing_slides_cnt = sum(1 for s in speakers if s.get("cohort") == "cohort_missing_slides")
    slides_ready_cnt = sum(1 for s in speakers if s.get("cohort") == "cohort_slides_available")
    orgs_cnt = len(organizers)
    ext_orgs_cnt = len(existing_ext_orgs)

    contacts_data["cohorts_summary"] = {
        "cohort_organizers": orgs_cnt,
        "cohort_missing_slides": missing_slides_cnt,
        "cohort_slides_available": slides_ready_cnt,
        "cohort_external_organizers": ext_orgs_cnt,
    }

    # Save contacts.json
    contacts_path.parent.mkdir(parents=True, exist_ok=True)
    with open(contacts_path, "w", encoding="utf-8") as f:
        json.dump(contacts_data, f, indent=2, ensure_ascii=False)

    # Update contacts_summary.json
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_payload = {
        "updated_at": contacts_data["updated_at"],
        "total_speakers": len(speakers),
        "total_organizers": orgs_cnt,
        "cohort_organizers_count": orgs_cnt,
        "cohort_missing_slides_count": missing_slides_cnt,
        "cohort_slides_available_count": slides_ready_cnt,
        "cohort_external_organizers_count": ext_orgs_cnt,
    }
    with open(summary_path, "w", encoding="utf-8") as sf:
        json.dump(summary_payload, sf, indent=2, ensure_ascii=False)

    return {
        "status": "success",
        "total_external_organizers": len(existing_ext_orgs),
        "newly_imported": newly_imported,
        "updated_count": updated_count,
        "conferences_processed": len(manifest_data.get("conferences", [])),
    }


def main():
    parser = argparse.ArgumentParser(description="Import External Tech Conference Organizers from KIMI Swarm Manifest")
    parser.add_argument("--input", default=str(DEFAULT_INPUT), help="Path to external_conferences.json")
    parser.add_argument("--contacts", default=str(DEFAULT_CONTACTS), help="Path to contacts.json")
    parser.add_argument("--summary", default=str(DEFAULT_SUMMARY), help="Path to contacts_summary.json")
    parser.add_argument("--db", default=str(DEFAULT_DB), help="Path to outreach_private.sqlite")
    args = parser.parse_args()

    result = import_external_conferences(
        input_path=args.input,
        contacts_path=args.contacts,
        summary_path=args.summary,
        db_path=args.db,
    )
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
